### ISSUE TITLE
extendedvideoexporter.asi preventing me from exporting but everything is downloaded correctly

### ISSUE THREAD

**Issue by buckzz123** [Z3do/Extended-Video-Export#3]

**Comment by buckzz123** [comment]
![Screenshot 2024-08-16 211259](https://github.com/user-attachments/assets/6191163d-492e-4acf-a74a-e1c2518bc6b6)
EVE folder is in subprocess and the asi file was in plugins

**Comment by Z3do** [comment]
Post your error on the forum  https://forum.cfx.re/t/how-to-use-extended-video-export-eve-fivem/2581771/606
